# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import food_pb2 as food__pb2


class FoodStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderFood = channel.unary_unary(
                '/Food/OrderFood',
                request_serializer=food__pb2.FoodRequest.SerializeToString,
                response_deserializer=food__pb2.FoodResponse.FromString,
                )


class FoodServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OrderFood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FoodServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderFood': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderFood,
                    request_deserializer=food__pb2.FoodRequest.FromString,
                    response_serializer=food__pb2.FoodResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Food', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Food(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OrderFood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Food/OrderFood',
            food__pb2.FoodRequest.SerializeToString,
            food__pb2.FoodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
